---
framework: mocha
postMerge:
  pattern:
    - "./test/*.js"
    - "./test/acceptance/*.js"
  strategy:
    threshold: <5|100s|30m|6h>
    type: <commit|time>
preMerge:
  pattern:
    - "./test/*.js"
    - "./test/acceptance/*.js"
preRun:
  - npm i
postRun:
  - node --version
version: 2.0
